import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from django.contrib.auth import get_user_model
from recipes.models import Recipe, Ingredient, Instruction, Nutrition

User = get_user_model()

print("Seed verileri yükleniyor...")

# Admin kullanıcı
if not User.objects.filter(email='admin@tarifkupu.com').exists():
    admin = User.objects.create_superuser(
        username='admin',
        email='admin@tarifkupu.com',
        password='admin123',
        name='Admin',
    )
    print("Admin kullanıcı oluşturuldu: admin@tarifkupu.com / admin123")
else:
    admin = User.objects.get(email='admin@tarifkupu.com')
    print("Admin kullanıcı zaten mevcut.")

RECIPES = [
    # ── KAHVALTI ──────────────────────────────────────────────
    {
        'title': 'Menemen',
        'description': 'Geleneksel Türk kahvaltısının vazgeçilmezi, domates ve biberli yumurta yemeği.',
        'category': 'breakfast',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 15,
        'servings': 2,
        'image_url': 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
        'rating': 4.8,
        'rating_count': 234,
        'ingredients': [
            ('Yumurta', '3 adet'),
            ('Domates', '2 adet'),
            ('Yeşil biber', '2 adet'),
            ('Soğan', '1 adet'),
            ('Zeytinyağı', '2 yemek kaşığı'),
            ('Tuz', 'Tadına göre'),
            ('Karabiber', 'Tadına göre'),
        ],
        'instructions': [
            'Soğanı ince ince doğrayın ve zeytinyağında kavurun.',
            'Biberleri küp küp doğrayıp soğanlarla birlikte soteleyin.',
            'Domatesleri rendeleyin veya küp doğrayıp tavaya ekleyin.',
            'Domatesler suyunu çekince yumurtaları kırın.',
            'Yumurtaları karıştırarak pişirin, tuz ve karabiber ekleyin.',
        ],
        'nutrition': {'calories': 220, 'protein': 14.0, 'carbs': 8.0, 'fat': 15.0},
    },
    {
        'title': 'Simit',
        'description': 'Susamlı, gevrek halkalı Türk sokak ekmeği. Kahvaltının olmazsa olmazı.',
        'category': 'breakfast',
        'difficulty': 'medium',
        'prep_time': 30,
        'cook_time': 20,
        'servings': 8,
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
        'rating': 4.7,
        'rating_count': 189,
        'ingredients': [
            ('Un', '500 gram'),
            ('Tuz', '1 çay kaşığı'),
            ('Kuru maya', '1 paket'),
            ('Su', '250 ml'),
            ('Pekmez', '3 yemek kaşığı'),
            ('Susam', '1 su bardağı'),
        ],
        'instructions': [
            'Unu, tuzu ve mayayı karıştırın, ılık su ekleyerek yoğurun.',
            '1 saat mayalanmaya bırakın.',
            'Hamuru halka şekline getirin.',
            'Pekmezli suya batırıp susama bulayın.',
            '200°C fırında 20 dakika pişirin.',
        ],
        'nutrition': {'calories': 280, 'protein': 9.0, 'carbs': 52.0, 'fat': 4.0},
    },
    {
        'title': 'Börek (Peynirli)',
        'description': 'Çıtır yufkalar arasında beyaz peynir ve maydanoz dolu nefis Türk böreği.',
        'category': 'breakfast',
        'difficulty': 'medium',
        'prep_time': 25,
        'cook_time': 35,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800',
        'rating': 4.9,
        'rating_count': 315,
        'ingredients': [
            ('Yufka', '3 adet'),
            ('Beyaz peynir', '300 gram'),
            ('Yumurta', '2 adet'),
            ('Süt', '100 ml'),
            ('Zeytinyağı', '50 ml'),
            ('Maydanoz', '1 demet'),
            ('Susam', '2 yemek kaşığı'),
        ],
        'instructions': [
            'Peyniri ufalayın ve kıyılmış maydanozla karıştırın.',
            'Yumurta, süt ve zeytinyağını çırpın.',
            'Tepsiye yufkayı serin, yarısını yumurtalı karışımla ıslatın.',
            'Peynirli harcı yayın, kalan yufkayı üstüne katlayın.',
            'Üzerine yumurtalı karışım ve susam serpin, 180°C\'de 35 dakika pişirin.',
        ],
        'nutrition': {'calories': 340, 'protein': 16.0, 'carbs': 32.0, 'fat': 18.0},
    },

    # ── ÇORBALAR ──────────────────────────────────────────────
    {
        'title': 'Mercimek Çorbası',
        'description': 'Türk mutfağının en sevilen çorbası, besleyici ve lezzetli kırmızı mercimek çorbası.',
        'category': 'soup',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 30,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        'rating': 4.9,
        'rating_count': 412,
        'ingredients': [
            ('Kırmızı mercimek', '2 su bardağı'),
            ('Soğan', '1 adet'),
            ('Havuç', '1 adet'),
            ('Patates', '1 adet'),
            ('Domates salçası', '1 yemek kaşığı'),
            ('Zeytinyağı', '3 yemek kaşığı'),
            ('Kimyon', '1 çay kaşığı'),
            ('Tuz', 'Tadına göre'),
        ],
        'instructions': [
            'Soğanı doğrayıp zeytinyağında kavurun.',
            'Salçayı ekleyip 2 dakika daha kavurun.',
            'Mercimek, havuç ve patatesi ekleyin.',
            '6 su bardağı su ekleyip 25-30 dakika pişirin.',
            'Blender ile pürüzsüz hale getirin ve kimyon ekleyin.',
        ],
        'nutrition': {'calories': 180, 'protein': 10.0, 'carbs': 28.0, 'fat': 4.0},
    },
    {
        'title': 'Ezogelin Çorbası',
        'description': 'Kırmızı mercimek, bulgur ve baharatların buluştuğu efsane Türk çorbası.',
        'category': 'soup',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 35,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=800',
        'rating': 4.8,
        'rating_count': 276,
        'ingredients': [
            ('Kırmızı mercimek', '1 su bardağı'),
            ('İnce bulgur', '3 yemek kaşığı'),
            ('Soğan', '1 adet'),
            ('Domates salçası', '2 yemek kaşığı'),
            ('Biber salçası', '1 yemek kaşığı'),
            ('Tereyağı', '2 yemek kaşığı'),
            ('Nane', '1 çay kaşığı'),
            ('Pul biber', '1 çay kaşığı'),
        ],
        'instructions': [
            'Soğanı yağda kavurun, salçaları ekleyin.',
            'Yıkanmış mercimeği ekleyip kavurun.',
            '6-7 su bardağı su döküp kaynatın.',
            'Bulguru ekleyip 20 dakika pişirin.',
            'Tereyağında nane ve pul biberi kavurup üzerine dökün.',
        ],
        'nutrition': {'calories': 195, 'protein': 11.0, 'carbs': 30.0, 'fat': 5.0},
    },
    {
        'title': 'Domates Çorbası',
        'description': 'Taze domateslerden yapılan, kremalı ve aromalı klasik domates çorbası.',
        'category': 'soup',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 25,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1613844237701-8f3664fc2eff?w=800',
        'rating': 4.5,
        'rating_count': 198,
        'ingredients': [
            ('Domates', '6 adet'),
            ('Soğan', '1 adet'),
            ('Sarımsak', '3 diş'),
            ('Tereyağı', '2 yemek kaşığı'),
            ('Krema', '100 ml'),
            ('Tavuk suyu', '500 ml'),
            ('Fesleğen', '5-6 yaprak'),
            ('Tuz, karabiber', 'Tadına göre'),
        ],
        'instructions': [
            'Soğan ve sarımsağı tereyağında kavurun.',
            'Doğranmış domatesleri ekleyip 10 dakika pişirin.',
            'Tavuk suyunu ekleyip kaynayınca 15 dakika daha pişirin.',
            'Blender ile pürüzsüz hale getirin.',
            'Kremayı ve fesleğeni ekleyip servis yapın.',
        ],
        'nutrition': {'calories': 150, 'protein': 4.0, 'carbs': 14.0, 'fat': 9.0},
    },

    # ── ANA YEMEKLER ──────────────────────────────────────────
    {
        'title': 'Karnıyarık',
        'description': 'Kıymalı iç harçla doldurulmuş, fırında pişirilmiş nefis patlıcan yemeği.',
        'category': 'dinner',
        'difficulty': 'medium',
        'prep_time': 20,
        'cook_time': 45,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        'rating': 4.7,
        'rating_count': 198,
        'ingredients': [
            ('Patlıcan', '4 adet'),
            ('Kıyma', '300 gram'),
            ('Soğan', '2 adet'),
            ('Domates', '2 adet'),
            ('Yeşil biber', '3 adet'),
            ('Sarımsak', '3 diş'),
            ('Zeytinyağı', '4 yemek kaşığı'),
            ('Maydanoz', '1 demet'),
        ],
        'instructions': [
            'Patlıcanları yarıya kesin, tuzlu suda 15 dakika bekletin.',
            'Kızgın yağda patlıcanları kızartın.',
            'Kıymayı soğanla kavurun, baharatları ekleyin.',
            'Patlıcanların içini açıp kıymalı harcı doldurun.',
            'Üzerine domates ve biber dilimleri koyun, fırında 30 dakika pişirin.',
        ],
        'nutrition': {'calories': 380, 'protein': 22.0, 'carbs': 18.0, 'fat': 24.0},
    },
    {
        'title': 'İmam Bayıldı',
        'description': 'Zeytinyağlı, soğan ve domatesle hazırlanan klasik Türk patlıcan yemeği.',
        'category': 'lunch',
        'difficulty': 'medium',
        'prep_time': 20,
        'cook_time': 40,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        'rating': 4.6,
        'rating_count': 143,
        'ingredients': [
            ('Patlıcan', '3 adet'),
            ('Soğan', '3 adet'),
            ('Domates', '3 adet'),
            ('Sarımsak', '4 diş'),
            ('Zeytinyağı', '100 ml'),
            ('Maydanoz', '1 demet'),
            ('Tuz', 'Tadına göre'),
            ('Şeker', '1 çay kaşığı'),
        ],
        'instructions': [
            'Patlıcanları boyuna yarın, tuzlu suda çekdirin.',
            'Soğanları halka halka doğrayıp zeytinyağında kavurun.',
            'Sarımsak ve domatesleri ekleyip pişirin.',
            'Patlıcanların içine harcı doldurun.',
            'Üzerine zeytinyağı gezdirip kısık ateşte 35 dakika pişirin.',
        ],
        'nutrition': {'calories': 220, 'protein': 4.0, 'carbs': 20.0, 'fat': 14.0},
    },
    {
        'title': 'Tavuk Şiş',
        'description': 'Baharatlarla marine edilmiş, ızgarada pişirilmiş lezzetli tavuk şiş kebabı.',
        'category': 'dinner',
        'difficulty': 'easy',
        'prep_time': 30,
        'cook_time': 20,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        'rating': 4.7,
        'rating_count': 321,
        'ingredients': [
            ('Tavuk göğsü', '600 gram'),
            ('Yoğurt', '3 yemek kaşığı'),
            ('Zeytinyağı', '2 yemek kaşığı'),
            ('Salça', '1 yemek kaşığı'),
            ('Sarımsak', '3 diş'),
            ('Kimyon', '1 çay kaşığı'),
            ('Pul biber', '1 çay kaşığı'),
            ('Tuz ve karabiber', 'Tadına göre'),
        ],
        'instructions': [
            'Tavukları küp küp doğrayın.',
            'Yoğurt, zeytinyağı ve baharatları karıştırın.',
            'Tavukları marine sosuyla karıştırıp 2 saat bekletin.',
            'Şişlere dizerek ızgarada her tarafını pişirin.',
            'Yanında pilav veya lavaş ile servis yapın.',
        ],
        'nutrition': {'calories': 310, 'protein': 40.0, 'carbs': 5.0, 'fat': 14.0},
    },
    {
        'title': 'Köfte',
        'description': 'Soğan ve baharatlarla yoğrulmuş, ızgarada pişirilmiş klasik Türk köftesi.',
        'category': 'dinner',
        'difficulty': 'easy',
        'prep_time': 20,
        'cook_time': 15,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800',
        'rating': 4.8,
        'rating_count': 445,
        'ingredients': [
            ('Kıyma', '500 gram'),
            ('Soğan', '1 adet'),
            ('Sarımsak', '2 diş'),
            ('Yumurta', '1 adet'),
            ('Ekmek içi', '2 dilim'),
            ('Kimyon', '1 çay kaşığı'),
            ('Pul biber', '½ çay kaşığı'),
            ('Maydanoz', 'Yarım demet'),
        ],
        'instructions': [
            'Soğan ve sarımsağı rendeleyin.',
            'Kıyma, soğan, sarımsak ve diğer malzemeleri yoğurun.',
            '30 dakika dinlendirin.',
            'Köfte şekli verin.',
            'Izgarada veya tavada her tarafını pişirin.',
        ],
        'nutrition': {'calories': 350, 'protein': 28.0, 'carbs': 8.0, 'fat': 22.0},
    },
    {
        'title': 'Kuzu Tandır',
        'description': 'Saatlerce yavaş pişirilen, yumuşacık ve lezzetli geleneksel kuzu tandır.',
        'category': 'dinner',
        'difficulty': 'hard',
        'prep_time': 30,
        'cook_time': 180,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        'rating': 4.9,
        'rating_count': 167,
        'ingredients': [
            ('Kuzu but', '1.5 kg'),
            ('Sarımsak', '8 diş'),
            ('Zeytinyağı', '4 yemek kaşığı'),
            ('Kekik', '2 yemek kaşığı'),
            ('Biberiye', '2 dal'),
            ('Soğan', '3 adet'),
            ('Havuç', '2 adet'),
            ('Tuz ve karabiber', 'Bol miktarda'),
        ],
        'instructions': [
            'Kuzu budu derin çiziklerle sarımsak yerleştirin.',
            'Zeytinyağı, kekik ve baharatlarla iyice ovun.',
            'Üzeri kapalı fırın kabına sebzelerle koyun.',
            '160°C\'de 2.5-3 saat yavaş pişirin.',
            'Son 20 dakika kapağı açıp kızartın.',
        ],
        'nutrition': {'calories': 480, 'protein': 45.0, 'carbs': 6.0, 'fat': 30.0},
    },
    {
        'title': 'Alabalık Tava',
        'description': 'Taze alabalığın unlanıp kızartılması ve limon sosuyla servis edilmesi.',
        'category': 'dinner',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 15,
        'servings': 2,
        'image_url': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
        'rating': 4.6,
        'rating_count': 134,
        'ingredients': [
            ('Alabalık', '2 adet'),
            ('Un', '4 yemek kaşığı'),
            ('Zeytinyağı', '3 yemek kaşığı'),
            ('Limon', '1 adet'),
            ('Sarımsak', '3 diş'),
            ('Tuz ve karabiber', 'Tadına göre'),
            ('Dereotu', '1 demet'),
        ],
        'instructions': [
            'Balıkları temizleyip içini ve dışını tuzlayın.',
            'İçine sarımsak ve dereotu koyun.',
            'Una bulayın.',
            'Zeytinyağında her tarafını kızartın.',
            'Limon dilimleriyle servis yapın.',
        ],
        'nutrition': {'calories': 290, 'protein': 38.0, 'carbs': 10.0, 'fat': 10.0},
    },
    {
        'title': 'Mantı',
        'description': 'El açması hamurun içine kıyma konulup haşlanmış, yoğurt ve salça sosuyla servis edilen Türk tortellini.',
        'category': 'lunch',
        'difficulty': 'hard',
        'prep_time': 90,
        'cook_time': 20,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
        'rating': 4.9,
        'rating_count': 389,
        'ingredients': [
            ('Un', '3 su bardağı'),
            ('Yumurta', '2 adet'),
            ('Kıyma', '250 gram'),
            ('Soğan', '1 adet'),
            ('Sarımsaklı yoğurt', '2 su bardağı'),
            ('Tereyağı', '3 yemek kaşığı'),
            ('Pul biber', '1 çay kaşığı'),
            ('Kuru nane', '1 çay kaşığı'),
        ],
        'instructions': [
            'Unu, yumurta ve su ile sert hamur yoğurun, 30 dk dinlendirin.',
            'İnce yuvarlak parçalar açıp kıymalı harçla doldurun.',
            'Kenarları sıkıştırarak kapatın.',
            'Tuzlu suda haşlayın.',
            'Sarımsaklı yoğurt döküp pul biberli tereyağı ile servis yapın.',
        ],
        'nutrition': {'calories': 420, 'protein': 22.0, 'carbs': 48.0, 'fat': 14.0},
    },
    {
        'title': 'Hünkârbeğendi',
        'description': 'Közlenmiş patlıcan püresi üzerine kuzu eti yahnisi dökülmüş osmanlı saray yemeği.',
        'category': 'dinner',
        'difficulty': 'hard',
        'prep_time': 30,
        'cook_time': 60,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
        'rating': 4.8,
        'rating_count': 112,
        'ingredients': [
            ('Kuzu kuşbaşı', '400 gram'),
            ('Patlıcan', '3 adet'),
            ('Tereyağı', '50 gram'),
            ('Un', '2 yemek kaşığı'),
            ('Süt', '250 ml'),
            ('Kaşar peyniri', '100 gram'),
            ('Domates', '2 adet'),
            ('Tuz, karabiber', 'Tadına göre'),
        ],
        'instructions': [
            'Kuzu etini tereyağında kavurun, domates ekleyip su ilave edin, 40 dk pişirin.',
            'Patlıcanları közde ya da fırında közleyin, kabuklarını soyun.',
            'Tereyağında unu kavurun, sütü yavaş yavaş ekleyerek béchamel yapın.',
            'Közlenmiş patlıcanı pürüzle ezip béchamele katın, kaşar rendeleyip karıştırın.',
            'Tabağa önce patlıcan püresi, üstüne yahniyi koyun.',
        ],
        'nutrition': {'calories': 510, 'protein': 32.0, 'carbs': 20.0, 'fat': 34.0},
    },

    # ── ÖĞLE YEMEKLERİ ────────────────────────────────────────
    {
        'title': 'Kısır',
        'description': 'İnce bulgur, domates, limon ve bol maydanozla hazırlanan ferah Türk salatası.',
        'category': 'lunch',
        'difficulty': 'easy',
        'prep_time': 20,
        'cook_time': 0,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
        'rating': 4.7,
        'rating_count': 231,
        'ingredients': [
            ('İnce bulgur', '2 su bardağı'),
            ('Domates salçası', '2 yemek kaşığı'),
            ('Biber salçası', '1 yemek kaşığı'),
            ('Zeytinyağı', '4 yemek kaşığı'),
            ('Limon suyu', '2 adet limon'),
            ('Maydanoz', '1 demet'),
            ('Yeşil soğan', '5 dal'),
            ('Nar ekşisi', '1 yemek kaşığı'),
        ],
        'instructions': [
            'Bulguru kaynar su ile ıslatıp demleyin.',
            'Soğuyunca salça, zeytinyağı ve limon suyunu ekleyip yoğurun.',
            'Doğranmış maydanoz ve yeşil soğanı katın.',
            'Nar ekşisi ile tatlandırın.',
            'En az 30 dakika buzdolabında bekletip servis yapın.',
        ],
        'nutrition': {'calories': 210, 'protein': 6.0, 'carbs': 36.0, 'fat': 6.0},
    },

    # ── TATLILAR ──────────────────────────────────────────────
    {
        'title': 'Baklava',
        'description': 'Antep fıstığı ve bal şerbeti ile hazırlanan Türk mutfağının en ünlü tatlısı.',
        'category': 'dessert',
        'difficulty': 'hard',
        'prep_time': 60,
        'cook_time': 40,
        'servings': 20,
        'image_url': 'https://images.unsplash.com/photo-1519915028121-7d3463d5b1ff?w=800',
        'rating': 4.9,
        'rating_count': 567,
        'ingredients': [
            ('Yufka', '500 gram'),
            ('Antep fıstığı', '300 gram'),
            ('Tereyağı', '200 gram'),
            ('Şeker', '2 su bardağı'),
            ('Su', '1.5 su bardağı'),
            ('Limon suyu', '1 yemek kaşığı'),
        ],
        'instructions': [
            'Şeker ve suyu kaynatarak şerbet hazırlayın, limon suyu ekleyin.',
            'Fıstıkları rondodan geçirin.',
            'Tepsiye yağlı yufkaları dizeyin, her katına eritilmiş tereyağı sürün.',
            'Ortasına fıstıkları yayın, kalan yufkaları üstüne koyun.',
            'Dilimleyip fırında altın rengi olana kadar pişirin, şerbet dökün.',
        ],
        'nutrition': {'calories': 420, 'protein': 7.0, 'carbs': 52.0, 'fat': 22.0},
    },
    {
        'title': 'Sütlaç',
        'description': 'Fırında üzeri kızarmış, kremsi ve lezzetli Türk pirinç pudingi.',
        'category': 'dessert',
        'difficulty': 'easy',
        'prep_time': 15,
        'cook_time': 50,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
        'rating': 4.8,
        'rating_count': 289,
        'ingredients': [
            ('Pirinç', '1 su bardağı'),
            ('Süt', '1 litre'),
            ('Şeker', '1 su bardağı'),
            ('Nişasta', '3 yemek kaşığı'),
            ('Su', '2 su bardağı'),
            ('Vanilya', '1 paket'),
        ],
        'instructions': [
            'Pirinci suda haşlayın.',
            'Süt ve şekeri ayrı bir tencerede ısıtın.',
            'Nişastayı soğuk suda eritip süte ekleyin.',
            'Haşlanmış pirinci ekleyip karıştırarak pişirin.',
            'Kaselere bölüp fırında üzerini kızartın.',
        ],
        'nutrition': {'calories': 280, 'protein': 7.0, 'carbs': 52.0, 'fat': 4.0},
    },
    {
        'title': 'Kazandibi',
        'description': 'Altı hafifçe kızarmış, tavuk göğsü içeren geleneksel Türk muhallebisi.',
        'category': 'dessert',
        'difficulty': 'medium',
        'prep_time': 20,
        'cook_time': 30,
        'servings': 6,
        'image_url': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800',
        'rating': 4.7,
        'rating_count': 178,
        'ingredients': [
            ('Süt', '1 litre'),
            ('Şeker', '150 gram'),
            ('Pirinç unu', '60 gram'),
            ('Nişasta', '40 gram'),
            ('Tavuk göğsü', '100 gram'),
            ('Vanilya', '1 paket'),
        ],
        'instructions': [
            'Tavuk göğsünü haşlayıp tel tel ayırın.',
            'Süt, şeker, un ve nişastayı karıştırarak kısık ateşte pişirin.',
            'Tavuğu ekleyip iyice karıştırın.',
            'Teflon tavada altı hafifçe kızarana kadar pişirin.',
            'Kaselere ters çevirip soğuyunca servis yapın.',
        ],
        'nutrition': {'calories': 260, 'protein': 9.0, 'carbs': 44.0, 'fat': 5.0},
    },
    {
        'title': 'Lokma',
        'description': 'Şeker şerbetinde bekletilmiş, dışı çıtır içi yumuşak Türk lokması.',
        'category': 'dessert',
        'difficulty': 'medium',
        'prep_time': 30,
        'cook_time': 20,
        'servings': 8,
        'image_url': 'https://images.unsplash.com/photo-1533910534207-90f31029a78e?w=800',
        'rating': 4.6,
        'rating_count': 203,
        'ingredients': [
            ('Un', '2 su bardağı'),
            ('Kuru maya', '1 paket'),
            ('Tuz', '1 çay kaşığı'),
            ('Su', '300 ml'),
            ('Şeker', '2 su bardağı (şerbet için)'),
            ('Su', '1 su bardağı (şerbet için)'),
            ('Kızartma yağı', 'Derin kızartma için'),
        ],
        'instructions': [
            'Un, maya, tuz ve ılık suyu karıştırıp akışkan hamur yapın.',
            '45 dakika mayalanmaya bırakın.',
            'Şeker ve suyu kaynatarak şerbet hazırlayın.',
            'Hamuru kaşıkla yağa bırakıp altın rengine kızartın.',
            'Sıcakken şerbete batırıp servis yapın.',
        ],
        'nutrition': {'calories': 320, 'protein': 4.0, 'carbs': 58.0, 'fat': 9.0},
    },
    {
        'title': 'Revani',
        'description': 'İrmik ve şerbetten yapılan, üzeri Hindistan cevizi kaplı nefis Türk tatlısı.',
        'category': 'dessert',
        'difficulty': 'easy',
        'prep_time': 15,
        'cook_time': 30,
        'servings': 12,
        'image_url': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
        'rating': 4.6,
        'rating_count': 156,
        'ingredients': [
            ('İrmik', '1.5 su bardağı'),
            ('Un', '0.5 su bardağı'),
            ('Şeker', '1 su bardağı'),
            ('Yumurta', '3 adet'),
            ('Zeytinyağı', '0.5 su bardağı'),
            ('Şeker (şerbet)', '2 su bardağı'),
            ('Su (şerbet)', '2 su bardağı'),
            ('Hindistan cevizi', 'Üzeri için'),
        ],
        'instructions': [
            'Yumurta ve şekeri çırpın.',
            'İrmik, un ve zeytinyağını ekleyip karıştırın.',
            'Yağlanmış tepsiye dökün, 180°C\'de 30 dakika pişirin.',
            'Şeker ve suyu kaynatarak şerbet hazırlayın.',
            'Sıcak tatlıya soğuk şerbet dökün, Hindistan cevizi serpin.',
        ],
        'nutrition': {'calories': 290, 'protein': 5.0, 'carbs': 50.0, 'fat': 8.0},
    },

    # ── ARA SICAKLAR ──────────────────────────────────────────
    {
        'title': 'Cacık',
        'description': 'Sarımsaklı yoğurt, salatalık ve nane ile hazırlanan serinletici Türk mezesi.',
        'category': 'snack',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 0,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
        'rating': 4.5,
        'rating_count': 176,
        'ingredients': [
            ('Süzme yoğurt', '500 gram'),
            ('Salatalık', '2 adet'),
            ('Sarımsak', '2 diş'),
            ('Zeytinyağı', '2 yemek kaşığı'),
            ('Kuru nane', '1 çay kaşığı'),
            ('Tuz', 'Tadına göre'),
        ],
        'instructions': [
            'Salatalıkları rendeleyin veya küçük küp doğrayın.',
            'Sarımsakları ezin.',
            'Yoğurt, salatalık ve sarımsağı karıştırın.',
            'Zeytinyağı, nane ve tuzu ekleyin.',
            'Soğuk servis yapın.',
        ],
        'nutrition': {'calories': 120, 'protein': 6.0, 'carbs': 8.0, 'fat': 7.0},
    },
    {
        'title': 'Sigara Böreği',
        'description': 'İçi peynir ya da kıymalı, çıtır çıtır kızarmış rulo börekler.',
        'category': 'snack',
        'difficulty': 'medium',
        'prep_time': 30,
        'cook_time': 15,
        'servings': 10,
        'image_url': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
        'rating': 4.8,
        'rating_count': 342,
        'ingredients': [
            ('Yufka', '3 adet'),
            ('Beyaz peynir', '250 gram'),
            ('Maydanoz', 'Yarım demet'),
            ('Yumurta', '1 adet'),
            ('Kızartma yağı', 'Derin kızartma için'),
        ],
        'instructions': [
            'Peyniri ufalayıp maydanozla karıştırın.',
            'Yufkayı üçgen şeklinde kesin.',
            'Geniş tarafına peynirli harcı koyun.',
            'Sıkıca rulo yapın, kenarını yumurtayla yapıştırın.',
            'Kızgın yağda altın renginde kızartın.',
        ],
        'nutrition': {'calories': 180, 'protein': 8.0, 'carbs': 16.0, 'fat': 10.0},
    },

    # ── SALATALAR ─────────────────────────────────────────────
    {
        'title': 'Çoban Salatası',
        'description': 'Domates, salatalık, biber ve soğanın zeytinyağıyla buluştuğu taze Türk salatası.',
        'category': 'salad',
        'difficulty': 'easy',
        'prep_time': 10,
        'cook_time': 0,
        'servings': 4,
        'image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        'rating': 4.6,
        'rating_count': 287,
        'ingredients': [
            ('Domates', '3 adet'),
            ('Salatalık', '2 adet'),
            ('Yeşil biber', '2 adet'),
            ('Kırmızı soğan', '1 adet'),
            ('Maydanoz', 'Yarım demet'),
            ('Zeytinyağı', '3 yemek kaşığı'),
            ('Limon suyu', '1 adet'),
            ('Tuz', 'Tadına göre'),
        ],
        'instructions': [
            'Tüm sebzeleri küçük küp doğrayın.',
            'Maydanozu ince kıyın.',
            'Hepsini geniş bir kaba alın.',
            'Zeytinyağı, limon suyu ve tuzu ekleyin.',
            'Karıştırıp servis yapın.',
        ],
        'nutrition': {'calories': 90, 'protein': 2.0, 'carbs': 10.0, 'fat': 5.0},
    },
]

Recipe.objects.all().delete()
print("Eski tarifler silindi.")

for data in RECIPES:
    recipe = Recipe.objects.create(
        title=data['title'],
        description=data['description'],
        category=data['category'],
        difficulty=data['difficulty'],
        prep_time=data['prep_time'],
        cook_time=data['cook_time'],
        servings=data['servings'],
        image_url=data['image_url'],
        rating=data['rating'],
        rating_count=data['rating_count'],
        author=admin,
    )

    for name, amount in data['ingredients']:
        Ingredient.objects.create(recipe=recipe, name=name, amount=amount)

    for step, description in enumerate(data['instructions'], start=1):
        Instruction.objects.create(recipe=recipe, step=step, description=description)

    n = data['nutrition']
    Nutrition.objects.create(
        recipe=recipe,
        calories=n['calories'],
        protein=n['protein'],
        carbs=n['carbs'],
        fat=n['fat'],
    )

    print(f"  ✓ {recipe.title}")

print(f"\nToplam {Recipe.objects.count()} tarif yüklendi.")
print("Seed tamamlandı!")
