# Generated by Django 6.0.1 on 2026-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('dessert', 'Tatlı'), ('snack', 'Ara Sıcak'), ('soup', 'Çorba'), ('salad', 'Salata')], default='dinner', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='medium', max_length=10)),
                ('prep_time', models.PositiveIntegerField(help_text='Dakika cinsinden hazırlık süresi')),
                ('cook_time', models.PositiveIntegerField(help_text='Dakika cinsinden pişirme süresi')),
                ('servings', models.PositiveIntegerField(default=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('image_url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
